const list = [
    {
      id: 1,
      title: "Nike Air Force 1",
      desc: "A classic sneaker known for its timeless design and versatility.",
      price: 89,
      img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9f79e2ec-95b9-4474-b022-7685f89b4650/air-force-1-07-shoes-5fFrTT.png",
      amount: 1,
    },
    {
      id: 2,
      title: "Adidas Ultraboost",
      desc: "Renowned for its comfort and cushioning, ideal for running and everyday wear.",
      price: 98,
      img: "https://assets.adidas.com/images/w_600,f_auto,q_auto/b167fd83945f414bbfdbf637efba5a01_9366/ULTRABOOST_1.0_SHOES_White_ID5879_01_00_standard.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Converse Chuck Taylor All Star",
      desc: "An iconic canvas sneaker with a rich history and casual style.",
      price: 143,
      img: "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw8711f6cf/images/d_08/M9160_D_08X1.jpg?sw=406",
      amount: 1,
    },
    {
      id: 4,
      title: "Nike Air Jordan 1",
      desc: "A legendary basketball shoe with a significant cultural impact and stylish design.",
      price: 57,
      img: "https://images-cdn.ubuy.co.in/634d139d183a133e4d32eaea-nike-air-jordan-1-high-og-unc-university.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "New Balance 990v5",
      desc: "A popular choice for its superior comfort, quality, and retro aesthetic.",
      price: 149,
      img: "https://imagedelivery.net/2DfovxNet9Syc-4xYpcsGg/966e354e-6863-4eb7-08ad-3e106b50e500/product",
      amount: 1,
    },
    {
      id: 6,
      title: "Adidas Stan Smith",
      desc: "A minimalist tennis shoe that has become a staple in casual fashion.",
      price: 135,
      img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b47d77eba6f945ea8dabac210127b11e_9366/Stan_Smith_Shoes_White_FX5501_01_standard.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Vans Old Skool",
      desc: "A classic skate shoe with a distinctive side stripe and durable design.",
      price: 693,
      img: "https://5.imimg.com/data5/ANDROID/Default/2023/1/OW/CO/WQ/154736600/product-jpeg.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Puma Suede Classic",
      desc: "Known for its sleek silhouette and soft suede upper, suitable for various casual looks.",
      price: 289,
      img: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374915/01/sv01/fnd/KOR/fmt/png/Suede-Classic-XXI-Unisex-Sneakers",
      amount: 1,
    },
    {
      id: 9,
      title: "Asics Gel-Kayano 27",
      desc: "A top-tier running shoe praised for its stability and cushioning.",
      price: 80,
      img: "https://assets.solesense.com/en/images/products/500/asics-gel-kayano-27-french-blue-1011b146-400_1.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Reebok Classic Leather",
      desc: "A versatile sneaker that combines retro style with modern comfort.",
      price: 86,
      img: "https://images.reebok.eu/19/72/95/81/19729581_44793750_2048.jpg?c=1",
      amount: 1,
    },
    {
      id: 11,
      title: "Hoka One One Clifton 8",
      desc: "Celebrated for its lightweight design and exceptional comfort, ideal for long-distance running and everyday wear.",
      price: 120,
      img: "https://www.hoka.com/on/demandware.static/-/Library-Sites-HOKA-EMEA-SHARED/default/dw2cec99ea/images/2021/Clifton-8/S21-Clifton-3.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Brooks Ghost 14",
      desc: "A highly regarded running shoe known for its balanced cushioning and smooth ride.",
      price: 157,
      img: "https://res.cloudinary.com/dr9fn4qkg/image/upload/w_400/brooks-images/product-img/120356_026_l_wr.png",
      amount: 1,
    },
];

export default list;